blueprint:
  name: LORA Universal Command
  description: Обрабатывает команды от LORA через MQTT (turn_on, turn_off, set)
  domain: automation
  source_url: https://github.com/YOUR_GITHUB/lora-blueprints/blob/main/lora_universal_command.yaml
  input: {}

trigger:
  platform: mqtt
  topic: lora/control

variables:
  parts: "{{ trigger.payload.split(' ') }}"
  cmd: "{{ parts[0] }}"
  entity: "{{ parts[1] }}"
  value: "{{ parts[3] if parts|length > 3 else None }}"

